var express = require('express');
var admin = express.Router();
admin.post('/login', require('./admin/login'));
admin.get('/isLogin', require('./admin/isLogin'));
admin.post('/loginOut', require('./admin/loginOut'));
admin.post('/user', require('./admin/addUser'));
admin.post('/uploads', require('./admin/uploads'));
admin.get('/showUsers', require('./admin/showUsers'));
admin.get('/user/:id', require('./admin/findUserById'));
admin.put('/user/:id', require('./admin/modifyUser'));
admin.delete('/user/:id', require('./admin/deleteUser'));
admin.put('/pwd', require('./admin/modifyPassword'));
module.exports = admin;