const express = require('express');
const article = express.Router();
article.post('/category', require('./article/addCategory'));
article.get('/category/:id', require('./article/findCategoryByid'));
article.get('/listCategory', require('./article/listCategory'));
article.put('/category/:id', require('./article/modifyCategoryById'));
article.delete('/category/:id', require('./article/deleteCategory'));
article.post('/uploads', require('./article/uploadsArticlePicture'));
article.post('/add', require('./article/addArticle'));
article.get('/showArticles', require('./article/showAritcles'));
module.exports = article;